"""Fixed prompt set shared by all benchmark runners."""

PROMPTS: list[str] = [
    "Explain why the sky appears blue to a curious twelve-year-old, using one everyday analogy and ending with three memorable facts.",
    "Write a respectful email asking a professor for a two-day assignment extension after an unexpected family obligation disrupted my schedule.",
    "Compare solar and wind power for a small coastal town, considering reliability, maintenance, land use, and environmental impact.",
    "Create a seven-step morning routine for someone who works from home and wants better focus without checking their phone immediately.",
    "Summarize the causes of the French Revolution in plain language, separating long-term pressures from the events that triggered the uprising.",
    "Draft a friendly product description for a reusable stainless-steel water bottle aimed at hikers who value durability and simple design.",
    "Explain recursion in programming with a concrete example, then mention one common mistake beginners make when writing recursive functions.",
    "Suggest five vegetarian dinners that use inexpensive pantry ingredients, take under forty minutes, and produce useful leftovers for lunch.",
    "Write a short dialogue between a cautious astronaut and an enthusiastic botanist discovering an unfamiliar plant inside an abandoned station.",
    "Describe how compound interest works using a simple numerical example, and explain why starting early matters more than investing large amounts later.",
    "Turn this goal into a practical weekly plan: improve public speaking confidence while working full time and avoiding expensive classes.",
    "Explain the difference between correlation and causation with two original examples drawn from ordinary life rather than medical research.",
    "Create a checklist for reviewing a pull request, covering correctness, readability, tests, security, performance, and backward compatibility.",
    "Write a calm response to a customer whose package arrived damaged, acknowledging the problem and offering clear replacement or refund options.",
    "Describe the water cycle as a journey narrated by a single raindrop, while keeping every scientific stage accurate and understandable.",
    "Recommend a balanced three-day itinerary for a first visit to Kyoto, mixing historic sites, quiet neighborhoods, food, and reasonable travel time.",
    "Explain what an API is to a nontechnical restaurant owner by comparing requests, responses, authentication, and errors to familiar restaurant activities.",
    "Provide six interview questions for a junior data analyst role and briefly state what a strong answer should demonstrate.",
    "Rewrite a vague goal about getting healthier into three measurable monthly objectives involving sleep, movement, and home-cooked meals.",
    "Outline both sides of a debate about remote work, including productivity, collaboration, accessibility, commuting, and employee well-being.",
    "Write a concise mystery opening set in a nearly empty train station where the departure board displays one impossible destination.",
    "Explain how vaccines train the immune system without using military metaphors, and distinguish normal side effects from the disease itself.",
    "Create a troubleshooting guide for a laptop that connects to Wi-Fi but cannot load websites, ordered from simplest checks to advanced ones.",
    "Suggest a fair method for dividing household chores among three roommates with different schedules, preferences, and standards of cleanliness.",
    "Summarize the central idea of opportunity cost, then apply it to choosing between graduate school and accepting a full-time job.",
    "Write an encouraging note for a friend who failed an important exam, avoiding clichés and offering specific, practical support.",
    "Design a twenty-minute beginner workout requiring no equipment, with a warm-up, low-impact exercises, rest guidance, and a cooldown.",
    "Explain why seasons occur on Earth, correct the common distance-from-the-Sun misconception, and describe conditions in both hemispheres.",
    "Propose five names for a neighborhood bookshop and café, giving a one-sentence rationale and distinct personality for each name.",
    "Create a simple budget for a student with irregular freelance income, emphasizing essential costs, emergency savings, and flexible spending limits.",
    "Describe the trade-offs between a relational database and a document database for an online marketplace with rapidly changing product attributes.",
    "Write a polite message declining a meeting that lacks an agenda while inviting the organizer to share goals asynchronously.",
    "Explain photosynthesis in four stages and connect each stage to the plant structures, inputs, and outputs involved.",
    "Generate eight thoughtful questions a traveler could ask local residents to learn about a city without treating them like tour guides.",
    "Draft a one-minute speech welcoming new volunteers to a community garden and explaining how their work will benefit the neighborhood.",
    "Compare renting and buying a home without recommending either, highlighting mobility, maintenance, upfront costs, uncertainty, and long-term equity.",
    "Write a debugging plan for an application that became slower after deployment even though unit tests and local benchmarks still pass.",
    "Explain the prisoner's dilemma using a workplace scenario, then identify what conditions can make cooperation more likely over time.",
    "Create a packing list for a rainy five-day hiking trip, grouping essentials by clothing, shelter, food, navigation, and safety.",
    "Summarize how a bill becomes law in the United States, including committee review, both chambers, reconciliation, and presidential action.",
    "Write a vivid but factual paragraph describing a coral reef at dawn without giving human emotions to animals or natural processes.",
    "Suggest four ways a small nonprofit can measure newsletter effectiveness beyond open rates, with one limitation for each metric.",
    "Explain binary search step by step on a sorted list, and state the assumption that makes its performance possible.",
    "Create a decision matrix for choosing between cycling, public transit, and driving for a daily eight-kilometer commute.",
    "Draft a clear apartment maintenance request about an intermittent ceiling leak, including timing, evidence, urgency, and access availability.",
    "Describe three ethical risks of facial recognition in public spaces and propose a concrete safeguard addressing each risk.",
    "Write a bedtime story about a tiny lighthouse keeper who solves a problem through patience, observation, and cooperation.",
    "Explain inflation to someone receiving their first salary, covering purchasing power, wage growth, savings, and changing interest rates.",
    "Develop a five-question survey for library visitors that produces actionable feedback without leading respondents toward positive answers.",
    "Compare unit tests, integration tests, and end-to-end tests using one consistent online shopping example across all three levels.",
    "Write instructions for giving constructive feedback to a teammate whose presentations contain strong research but unclear visual organization.",
    "Outline a low-waste plan for hosting dinner for eight people, considering shopping, preparation, serving, leftovers, and cleanup.",
    "Explain how a hash table stores and retrieves values, including collisions, average performance, and one situation where it performs poorly.",
    "Create a short museum audio-guide script introducing an ancient object while clearly separating known facts from scholarly interpretation.",
    "Suggest six screen-free activities for siblings aged eight and thirteen that encourage collaboration without requiring special equipment.",
    "Write a neutral summary of the arguments for and against requiring school uniforms, avoiding assumptions about families or students.",
    "Explain the difference between encryption and hashing, giving a practical use case for each and noting whether reversal is expected.",
    "Build a thirty-day reading habit plan for someone who currently struggles to finish books and has only fifteen minutes daily.",
    "Draft a brief announcement explaining a planned service outage, including affected features, timing, user preparation, and status updates.",
    "Describe how plate tectonics causes earthquakes and volcanoes, while distinguishing convergent, divergent, and transform plate boundaries.",
    "Propose a structured agenda for resolving a disagreement between design and engineering about the scope of an upcoming release.",
    "Write a recipe for a flexible vegetable soup that teaches how to substitute ingredients while keeping flavors and textures balanced.",
    "Explain the purpose of a constitution, comparing how it grants authority, limits power, protects rights, and enables institutional change.",
    "Create five reflection questions for someone deciding whether to leave a stable job for a risky but meaningful opportunity.",
]
